### ISSUE TITLE
Unable to see generated code in Github

### ISSUE THREAD

**Issue by ernsheong** [MarcGrol/golangAnnotations#4]
Hi there, 

Love the idea. The README points to generated examples, but they are 404 on Github. Mind checking in those links so that people can see? (or fix the links)

**Comment by MarcGrol** [comment]
Sorry for my late answer. Links indeed no longer work, because we no longer commit generated sources. Will remove them.
make install on the project will generate it so you will be able to see it.

I use golangAnnotations on a daily basis. 100.000 lines of our 200.000 lines project is generated this way.
